zeesh_plugins=(
    # OS-specific
    freebsd

    # Enable plugins
    autoenv
    git
    go
    javascript
    # kubernetes
    python
    virtualenv

    # Fancy command line
    history-substring-search
    syntax-highlighting

    # We live and breath vim here
    vi-mode

    # Need to come last
    theme
    vcs-info
    autocomplete
)
source ~/.zsh/zeesh.zsh

export PATH=~/.bin:~/.ellipsis/bin:$PATH
alias el=ellipsis
