zeesh_plugins=(
    freebsd
    vi-mode
    python
    django
    virtualenv
    haskell
    mercurial
    git
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
    upstart
    autocomplete
    iterm2
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=

export PATH=~/.bin:~/.ellipsis/bin:$PATH
alias el=ellipsis
