zeesh_plugins=(
    # OS-specific
    osx
    iterm2

    # We live and breath vim here
    vi-mode

    # Fancy command line
    autocomplete
    syntax-highlighting
    history-substring-search

    # Various plugins
    audio
    autoenv
    git
    go
    javascript
    kubernetes
    python
    virtualenv

    # Need to come last
    vcs-info
    theme
)
source ~/.zsh/zeesh.zsh

export PATH=~/.bin:~/.ellipsis/bin:$PATH
alias el=ellipsis
