zeesh_plugins=(
    osx
    vi-mode
    python
    django
    virtualenv
    haskell
    mercurial
    git
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
    upstart
    autocomplete
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=
export ELLIPSIS_PROTO=ssh
export PATH=~/.bin:~/.ellipsis/bin:$PATH
export GOPATH=$HOME/go
export PATH=$PATH:/usr/local/Cellar/go/1.2/libexec/bin:/usr/local/cuda/bin:$GOPATH/bin

alias git='noglob hub'
alias http='noglob http'
alias utc='date -u'
alias v=vim
alias sl=ls
alias clj='lein repl'
alias hd='noglob hoodoo'
alias ack=ag
alias cask='brew cask'
alias el=ellipsis

compctl -k "(new edit install uninstall unlink list links pull push status publish search --version --help)" ellipsis

if [ -e ~/.private/zsh ]; then
    source ~/.private/zsh
fi
