zeesh_plugins=(
    linux
    vi-mode
    git
    javascript
    python
    virtualenv
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
    autocomplete
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=

export PATH=~/.bin:~/.ellipsis/bin:$PATH
alias el=ellipsis
