zeesh_plugins=(
    linux
    vi-mode
    git
    python
    virtualenv
    vcs-info
    syntax-highlighting
    history-substring-search
    theme
    autocomplete
)
source ~/.zsh/zeesh.zsh

export ZEESH_THEME_NORMAL_CHAR='\n⊙'
export ZEESH_THEME_VISUAL_CHAR='\n⊡'
export ZEESH_THEME_INSERT_CHAR='\n›'
export ZEESH_THEME_PROMPT_CHAR=
export PATH=~/.bin:~/.ellipsis/bin:$PATH

alias utc='date -u'
alias v=vim
alias sl=ls
alias el=ellipsis
alias clj='lein repl'

compctl -k "(new edit install uninstall unlink list links pull push status publish search)" ellipsis

if [ -e ~/.private/zsh ]; then
    source ~/.private/zsh
fi
